### PR TITLE
Add more built-in delegates for ImageMagick: 

### PR DESCRIPTION
**Pull request by Ben305**
With these changes:
`bzlib djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png tiff wmf x xml zlib`

Without these changes:
`bzlib jng jpeg png x xml zlib`

I'd appreciate if this would be merged soon.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
thanks. I triggered rebuilding all the images, will take some time though

**Comment by Ben305** [comment]
@dpfaffenbauer Thanks for merging this so fast, JPEGs with CMYK-profile are not rendered correctly 👍

**Comment by dpfaffenbauer** [comment]
I guess you mean `now` right?

**Comment by Ben305** [comment]
Of course, sorry!

**Pull request merged**
